### PR TITLE
t-closeness analysis for randomly assigned cohorts w.r.t. race

### PR DESCRIPTION
**Pull request by aberke**
- using panel with the size of the chrome OT panel
- panel race distributions match ACS

### CODE REVIEW

**Comment by aberke** [comment]
Do not merge this PR until https://github.com/aberke/floc-analysis/pull/8 is merged.

This PR uses the panels and cohorts data generated by https://github.com/aberke/floc-analysis/pull/8.

**edit**
https://github.com/aberke/floc-analysis/pull/10 replaced https://github.com/aberke/floc-analysis/pull/8 to get around git LFS issues.

That PR must still be merged first. The notebooks must be run in order to generate the panels and cohorts data used in these notebooks.

**Comment by dcalacci** [comment]
as far as I can see is sensible. is there a specific place for me to examine that I might have overlooked?

**Comment by aberke** [comment]
Thanks for reviewing, @dcalacci. Were you able to fully run and reproduce all results?
Do you have any recommendations for how you might prefer the plots or results presented? 

Otherwise, please feel free to merge

**Comment by dcalacci** [comment]
Take a look at the updated notebook, `t-closeness-for-comscore-panels-by-race`. I updated it to calculate `t` at higher intervals while investigating the binomial Q, and added the new plotting code using ggplot and our styles.

**Comment by aberke** [comment]
For the new plots, y-axis shouldn't say %. I think it should say the same as Google's figure in their report: "Fraction of cohorts blocked".

Nice idea to reorganize with an appendix. I think further reorganize it so that the 'Appendix: Binomial models mimic random cohort data' section doesn't come before the other appendix section that is further below.

I think it is important to keep the panel size comparison :) It verifies n is consistent.

**Comment by aberke** [comment]
above issues resolved. Merging.

**Pull request merged**
