### PR TITLE
Panel domains race sensitivity

### PR DESCRIPTION
**Pull request by dcalacci**
Computing chi-square homogeneity tests for domain frequency between race groups in comscore data, and plotting frequencies.

I simply counted domain occurrences in the weeks-domains dataset. It occurred to me that we could examine a specific panel, or that we could examine week-by-week, but this overall approach is clear, and I think it's convincing. 

See `notebooks/sensitivity-by-race-by-domain-visit-frequency.ipynb` for details. 

Unsure of the best way to report chi2 results beyond p-val, which is what I've used in the past. Here, it's `0.0`, which...is good, but not illustrative :)

Unsure of the best way to *quantify* differences between domain distributions, to give the reader a sense of *how* different these distributions are, but may add more commits addressing that. 

Plots are helpful, particularly the faceted one towards the bottom of the notebook. 

Any other useful tidbits?

### CODE REVIEW

**Comment by aberke** [comment]
(draft review - will come back to complete)
Great work!

Suggestions overall: 

Compare just two populations (subsampled vs general) at a time when doing both chi-squared test (of homogeneity) and plots.

Also, create a randomly subsampled population from the general population and compare to general aggregate population as well. This might be an extremely point of comparison, especially given that we have an unusually large number of levels for our categorical variables (domain visits).

So here's how I might go about this:

compute domain frequencies for aggregate population (as you are)

consider 5 sampled populations: 4 are each race population + 1 is randomly subsampled from total population

test a variety of D_max values, where D_max is the N in the view of top N domains.
e.g. D_max in [10, 25, 50, 100]

for each D_max:
get top top D_max_domains for the total population (as you are)
get visit frequencies for each population (total and each of the 5 subsamples)

for each subsampled population:
(test / plot vs aggregate population separately)

chi-sq test of homogeneity 
null hypothesis: The proportion of visits to each domain in D_max_domains is the same between the aggregate population and subsampled population.

Test with a significance level of p=0.05 (good practice to choose upfront)

record p-value to collect in a table so that we can have a table like below where the row values are p-values

```
D_max, random subsample, white, black, asian, other
```


other changes we might want:

- clean up our rough notes at the top of the notebook (could replace with nicer description below [1])
- [updated - done] show output from cells
- [updated - done] clean up redundant code in bottom of [4]
- plots compare specific race to aggregate population for each race separately
- stylize plots to be consistent with t-closeness analysis?

**Comment by aberke** [comment]
pushed small changes to address a couple of above requested changes.

**Comment by aberke** [comment]
Rough notes:
for [43] - is col being used right?

for [41] I think this needs to instead compare each race to the aggregate population

**Comment by dcalacci** [comment]
Ready for review now. nice and clean, i think

**Comment by aberke** [comment]
fixes
- [1] defines TOP_N_DOMAINS = 50 -- but this is a variable that later changes
- [3] (nit) fpath defines year, year definition redundant
- description calls user population a cohort which is confusing because cohort is a very important word that means something very different everywhere else in this work.
- [8] hooray! thanks for considering my methodology nit from before
- [12] the docstring for chi_square_data is confusing (maybe outdated from a previous function?) - would be better to remove
- [21] cool table but shouldn't round p values so small. 
- methods question! What is happening in chi_square_pairwise ? I thought we wanted to compare each subpopulation to aggregate. Is that what is happening? 
- for the final table -- I think we want the top 100 since that is how far we test to 
- somewhere in this notebook it would be good to print on the N=total users and N for the subpopulations. We should report this in our appendix

**Comment by dcalacci** [comment]
- [x] remove old global variables
- [x] clean fpath
- [x] improve docstrings
- [x] can we get more detailed p-values?


> [21] cool table but shouldn't round p values so small.

Weirdly and unfortunately the p-values returned from the scipy method are literally `0.0` I think because they are so small. I'll look into how to get the real values if possible.

> methods question! What is happening in chi_square_pairwise ? I thought we wanted to compare each subpopulation to aggregate. Is that what is happening?

Yeah, the table that is reported here is looking at the overall marginal distribution (which is what `chi2_contingency` does), which is what we want & what you described. In another test in notebooks past, I compared distributions to each other but we don't use this anymore. i can remove this function. 

> for the final table -- I think we want the top 100 since that is how far we test to
somewhere in this notebook it would be good to print on the N=total users and N for the subpopulations. We should report this in our appendix

Sure. 100 is a bit long imo, nobody will care, but I can create it here and we can trim as needed in drafts

**Comment by aberke** [comment]
- for the p-value rounding issue. Maybe a non-issue. The point is scipy rounds for p<0.001 and we can just report that we had p<0.001.
- noted on methodology. I should have just run the code or learned what combinations does.
- for the table: D=100 is long. Let's do D=50 so that it matches what is shown in the Figure so that we can report the figure details. 10 certainly seems too small since it just represents the biggest tech companies.

**Pull request merged**
